version: "3.8"
services:
  screenshot-server:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    # Tùy chọn để chạy Puppeteer trong Docker
    cap_add:
      - SYS_ADMIN
    command: ["npm", "start"]
