version: '3.8'
services:
    screenshot-server:
        build: .
        volumes:
            - .:/app
            # Loại bỏ node_modules khỏi volume để sử dụng lớp node_modules được cài đặt trong image
            # - /app/node_modules
        ports:
            - '10000:10000'
        environment:
            NODE_ENV: development
        # Tùy chọn để chạy Puppeteer trong Docker
        cap_add:
            - SYS_ADMIN
        # Đã sửa command để phù hợp với cách chạy mới từ Dockerfile
        # command: ["npm", "start"]
